# DAX Trend-Following Trading System Configuration

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  temp_data_path: "data/temp"
  file_pattern: "*.csv"
  timezone_source: "America/Chicago"
  timezone_target: "Europe/Berlin"

# Feature Engineering
features:
  lookback_periods: [5, 10, 20, 50, 100, 200]
  ema_periods: [9, 21, 55]
  rsi_period: 14
  atr_period: 14
  volume_ma_period: 20

# Market Regime Detection
regime:
  min_regime_duration: 10  # minutes
  volatility_lookback: 100
  trend_threshold: 0.02

# Strategy Parameters
strategy:
  min_trend_strength: 0.7
  entry_confirmation_bars: 3
  max_positions: 3
  position_timeout: 480  # minutes (8 hours)

# Risk Management
risk:
  max_risk_per_trade: 0.005  # 0.01 = 1% of capital // curently 0.5% of capital
  stop_loss_atr_multiplier: 2.0
  take_profit_ratio: 2.0  # Risk:Reward
  max_daily_loss: 0.01  # 1% of capital

# Backtesting
backtest:
  initial_capital: 50000
  commission_rate: 0.0001  # 0.01%
  slippage: 0.0002  # 0.02%
  walk_forward_period: 252  # trading days
  
# System Settings
system:
  log_level: "INFO"
  max_cpu_cores: 8
  use_gpu: true
  random_seed: 42